TASK 1 

In [81]:
import random
import numpy as np

np.random.seed(0)

readings = np.random.normal(loc=50, scale=15, size=(360,4))

print("Shape:", readings.shape)
print("Data type:", readings.dtype)
print("First three rows:\n", readings[:3])

Shape: (360, 4)
Data type: float64
First three rows:
 [[76.46078519 56.00235813 64.68106976 83.61339799]
 [78.01336985 35.3408318  64.25132626 47.72964188]
 [48.45171722 56.15897753 52.16065357 71.8141026 ]]


TASK 2

In [82]:
min__vals = readings.min(axis=0)
max__vals = readings.max(axis=0)

scaled_readings = (readings - min__vals) / (max__vals - min__vals)

In [83]:
col_means = readings.mean(axis=0)
centered_readings = readings - col_means


In [84]:
print("Original shape:", readings.shape)
print("Scaled shape:", scaled_readings.shape)
print("Centered shape:", centered_readings.shape)


Original shape: (360, 4)
Scaled shape: (360, 4)
Centered shape: (360, 4)


TASK 3

In [85]:
outlier_mask = (readings > 80) | (readings < 20)
outlier_count = np.sum(outlier_mask)
total_readings = readings.size
outlier_percentage = ( outlier_count / total_readings ) * 100

print("Number of outliers:", outlier_count)
print("Percentage of outliers: {:.2f}%".format(outlier_percentage))

cleaned_readings = readings.copy()
cleaned_readings[outlier_mask] = np.nan


nan_count = np.isnan(cleaned_readings).sum()
print("Number of np.nan in cleaned array:", nan_count)

Number of outliers: 61
Percentage of outliers: 4.24%
Number of np.nan in cleaned array: 61


TASK 4

In [86]:
sensor_means = readings.mean(axis=0)
sensor_stds = readings.std(axis=0)
time_means = readings.mean(axis=1)


TASK 5

In [87]:
report_dict = {
    "total_readings": total_readings,
    "outlier_count": outlier_count,
    "outlier_percentage": outlier_percentage,
    "sensor_means": sensor_means,
    "sensor_stds": sensor_stds, 
}

print(f"Total readings count is: {total_readings} \nTotal outlier count is: {outlier_count} \nOutlier percentage is: {outlier_percentage:0.2f} \nSensor means are: {sensor_means} \nSensor stds are: {sensor_stds}")
print(f"Total readings count is the same as readings size: {total_readings == readings.size}")

Total readings count is: 1440 
Total outlier count is: 61 
Outlier percentage is: 4.24 
Sensor means are: [49.44542203 48.73041473 50.08340854 50.39910733] 
Sensor stds are: [14.64041833 14.54682259 14.64734462 15.03726472]
Total readings count is the same as readings size: True


TASK 6

In [88]:
np.random.seed(0)

sim = np.random.normal(loc=0, scale=1, size=(1000, 6))

print(f"Sim shape is: {sim.shape}")
print(f"Sim type is: {sim.dtype}")
print(f"First three rows are: \n{sim[:3]}")

Sim shape is: (1000, 6)
Sim type is: float64
First three rows are: 
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885  0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433  1.49407907 -0.20515826]]


TASK 7

In [89]:
scenario_shift = np.array([-0.3, -0.1, 0.0, 0.1, 0.2, 0.4])

adjusted_sim = sim + scenario_shift


print(f"Shapes are the same: {sim.shape == adjusted_sim.shape}")

original_means = sim.mean(axis=0)
adjusted_means = adjusted_sim.mean(axis=0)

print(f"Mean shift is: {original_means-adjusted_means}")

Shapes are the same: True
Mean shift is: [ 0.3  0.1  0.  -0.1 -0.2 -0.4]


TASK 8

In [90]:

scenario_means = adjusted_sim.mean(axis=0)
scenario_ranking = np.argsort(scenario_means)

partitioned_means = np.partition(scenario_means, -2)
top_two_partitioned = np.sort(partitioned_means[-2:]) 

full_sorted_means = np.sort(scenario_means)
top_two_sorted = full_sorted_means[-2:]

print(f"Scenario Means: {scenario_means}")
print(f"Ranking (Indices): {scenario_ranking}")
print(f"Top 2 match: {np.allclose(top_two_partitioned, top_two_sorted)}")

Scenario Means: [-0.35901134 -0.12738582 -0.03330027  0.13725843  0.20301273  0.38674278]
Ranking (Indices): [0 1 2 3 4 5]
Top 2 match: True


TASK 9

In [91]:

np.random.seed(0)
sim_2 = np.random.normal(loc=0, scale=1, size=(1000, 6))

np.random.seed(42)
sim_3 = np.random.normal(loc=0, scale=1, size=(1000, 6))

match_1_2 = np.array_equal(sim, sim_2)
match_1_3 = np.array_equal(sim, sim_3)

print(f"Does sim_2 match sim? {match_1_2}")
print(f"Does sim_3 match sim? {match_1_3}")
print(f"Number of identical elements in sim vs sim_3: {np.sum(sim == sim_3)} out of {sim.size}")

Does sim_2 match sim? True
Does sim_3 match sim? False
Number of identical elements in sim vs sim_3: 0 out of 6000


TASK 10

In [92]:

top_two_indices = scenario_ranking[-2:]
top_two_values = scenario_means[top_two_indices]

validation_report = {
    "shape": adjusted_sim.shape,
    "scenario_means": scenario_means,
    "top_two_indices": top_two_indices,
    "top_two_values": top_two_values
}

val_len_means = len(scenario_means) == 6
val_len_indices = len(top_two_indices) == 2

report_str = f"""
==========================================================
                 VALIDATION REPORT PART 2                 
==========================================================                 
Array Shape:         {validation_report['shape']}
Scenario Means:      {validation_report['scenario_means']}
Top 2 Indices:       {validation_report['top_two_indices']}
Top 2 Values:        {validation_report['top_two_values']}

VALIDATION CHECKS:
- Scenario means count is 6: {val_len_means}
- Top two indices count is 2: {val_len_indices}
==========================================================
"""
print(report_str)


                 VALIDATION REPORT PART 2                 
Array Shape:         (1000, 6)
Scenario Means:      [-0.35901134 -0.12738582 -0.03330027  0.13725843  0.20301273  0.38674278]
Top 2 Indices:       [4 5]
Top 2 Values:        [0.20301273 0.38674278]

VALIDATION CHECKS:
- Scenario means count is 6: True
- Top two indices count is 2: True

